### ISSUE TITLE
Fix README Grammatical Error

### ISSUE THREAD

**Issue by profsucrose** [neelr/tabroom-private-api#1]
> An API whipped up using tabroom's private api, because it took to long for them to give a public one! Have fun and make cool things!

"to" should be "too"

This is certainly the biggest software bug I've ever seen, fix it RIGHT NOW! Tank you very much!

**Comment by neelr** [comment]
no u

**Comment by profsucrose** [comment]
I need this to be fixed RIGHT NOW pweasy pwease pwease pwease

**Comment by neelr** [comment]
Yessir mate, I have successfully completed the operation. We shall now terminate this issue successfully with code 200. 🖖
